export default initialState = {
    userData: {
        device_token: '',
        info: {},
        token: '',
        charging_stations: '',
        distance: '',
        filter: '',
        current_location: {},
        reviews_list: '',
        vehicles_list: '',
        charging_station_info: '',
        charging_point_info: '',
        book_charger_info: '',
        booking_info: {},
        order_id: '',
        order_amount: 0.00,
        coupon_status: false,
        coupon_applied: {},
        subscribed:0,
        buycharger:'',
        franchisers:'',
        Chessis_no:'',
        remove:'',
        notification: 1,
        wishlist: [],
    }
};
